# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d27c4bc27499881b587c91f37e482146c1b7cd0765fb59783f2ee8406deea298260fe951e84df658d41bbfd521300cfd014409ff77c015d9ec22946f051c9d51

test:
  secret_key_base: 819d96eee464b44f89167785b1ff085ca5d9a2e0c87aafd204ec42a747c4011138ecdfe29ec5a7257ff2b869a3f888e3a5155dc66846b80ed75ab91cd3af4d8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
